name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to EC2 instance
        run: |
          ssh -o "StrictHostKeyChecking=no" -i ${{ secrets.EC2_PRIVATE_KEY }} user@ec2-instance 'mkdir -p /path/to/app'
          scp -o "StrictHostKeyChecking=no" -r ./ user@ec2-instance:/path/to/app

          # Puedes ejecutar comandos adicionales en el servidor si es necesario
          ssh -o "StrictHostKeyChecking=no" -i ${{ secrets.EC2_PRIVATE_KEY }} user@ec2-instance 'cd /path/to/app && npm install && npm start'
